italia/designers.italia.it

_includes/ipress_news.html
_pages/it/contatti.md
_plugins/IpressImporter.rb

Merge e fix contatti issuee  #19

Merge e fix contatti issuee #19

---

_projects/it/siti-scuole

Ecco pagina progetto con roadmap pubblica per siti scuole 
cc @matteodesanti
Avrei bisogno che la pagina venisse lincata dal menù progetti. Inoltre credo vada realizzata l'immagine di background (jpg)

Siti scuole

---

Gemfile
_config.yml
_layouts/credits.html
news/index.html

This commit upgrades our website to jekyll 3.5.x and Liquid 4.0.

Upgraded to jekyll-3.5.2

---

gulpfile.js

Added JEKYLL_ENV=production env variable

Set production environment variable

---

_projects/it/web-analytics.md

inseriti nuovi paragrafi PA onboarding + funzionalità core e premium Piwik
per check @sbronzolo (fammi sapere se preferisci che inserisca i link ai siti citati)

nuovo paragrafo onboarding piwik

---

_includes/home/block-3.html

Ho "spento" il bottone Ricerche qualitative, in attesa che la sezione sia chiusa
Ho allineato le linee giuoda di UI al toc effettivamente pubblicato sulle linee guida

Aggiornamento HP blocco 3

---

_includes/home/block-1.html
_includes/ipress.html
_includes/newsletter.html
_pages/it/contatti.md

Changes to “Contacts” page. Resolves #68.

Contact page improvements

---

_data/l10n.yml

Corregge 2 refusi nel testo introduttivo
Aggiunge link a guide e forum nel testo introduttivo

Aggiorna testo introduttivo in homepage

---

_includes/home/block-1.html
_sass/_designer.scss

Fix issue #63 introduced with #64

Fixed text rendering in homepage

---

news/index.html

Blog post date fix

---

_data/guidelines.yml

Ho associato dei tag a ogni capitolo e sottocapitolo. Come criterio, ho assegnato un massimo di 4 tag a voce.

Associa le tag per le linee guida

---

_plugins/MediumImporter.rb

Rimodulo il crop dell'immagine del post di medium per ottenere un esatta proporzione

Rimodulo il crop dell'immagine del post 

---

_kits/it/SEO.md
_kits/it/ui-kit.md
_kits/it/web-toolkit.md

Ciao, una PR per aggiungere al redesign la pagina UI e la pagina SEO, ovvero i due kit che ancora mancavano, e per inserire il link al Webtoolkit.

Francescomda patch redesign

---

_projects/it/web-analytics.md

Revisione 20.02 pagina progetto web analytics come concordato con @sbronzolo

Update 20.02 web-analytics.md

---

_data/guidelines.yml
_includes/home/block-3.html

Fixed broken links

---

Gemfile.lock
_kits/it/SEO.md
_kits/it/analytics.md
_kits/it/co-design-workshop.md
_kits/it/content-kit.md
_kits/it/ecosystem-map.md
_kits/it/information-architecture.md
_kits/it/personas.md
_kits/it/ui-kit.md
_kits/it/usability-test.md
_kits/it/user-interviews.md
_kits/it/user-journey.md
_kits/it/user-stories.md
_kits/it/web-toolkit.md
_kits/it/wireframe-kit.md
_layouts/download.html
_layouts/post.html
_pages/it/roadmap.md

Miglioramento della gestione della "description" sui kits, sostituendo "subtitle" con apposito campo "description"

Miglioramento della gestione della "description" sui kits

---

_kits/it/personas.md
assets/downloads/KIT_Personas_Esercizio.pdf
assets/downloads/KIT_personas_esercizio.pdf

Sostituito il PDF per un typo segnalato. Visto che c'ero ho uniformato il titolo (e il nome del file) agli altri kit, con le iniziali maiuscole.

Fix Kit personas (typo "qual'è")

---

_data/roadmap.yml
_includes/roadmap.html
_sass/_designer.scss

L'ho impostata. Francesco Zaia dai una occhiata per favore alla schedulazione di ui kit e kit frontend
Meglio inserire milestone credibili invece di affollare troppe cose in pochi mesi.
Inoltre il it "app desktop" è un oggetto a me poco chiaro allo stato attuale (e non so quanto prioritario, se ho capito di cosa si tratta)

Update roadmap e nuove milestone

---

_kits/it/usability-test.md

Aggiornato link in modalità sola visualizzazione

modifica link doc "Guida partecipanti"

---

_kits/it/usability-test.md

Correzione link "Guida partecipanti"

Correzione link "Guida partecipanti"

---

_kits/it/content-kit.md
_kits/it/usability-test.md
_kits/it/user-interviews.md

Aggiunge il file "liberatoria" al content kit 
+ aggiorna i link a i file riveduti e corretti da Agid in base a nuove regole GDPR delle liberatorie di User Interviews e Usability test

Francescomda patch 1

---

.circleci/config.yml

In case other people should have to do with that snippet.

Document the SSH_KNOWN_HOST content

---

_includes/newsletter.html

Edits:
- `action` and `method` form attributes
- `name` attribute for email input field
- added anti spam input field

Moved newsletter subscription from MailUp to MailChimp

---

_data/menu_items.yml
_data/roadmap.yml
_projects/it/siti-web-comuni.md
_projects/it/siti-web-pa.md
_projects/it/siti-web-scuole.md
_projects/it/web-analytics-italia.md
_projects/it/web-analytics.md

Nuova pagina Web Analytics Italia, rivisti alcuni URL, mini aggiornamento roadmap.

Web Analytics Italia

---

_includes/newsletter.html

Go back to Mailup and remove Mailchimp.
This reverts commit 7763ea751d9d55087ebec0db9f64d4ee7da23765.

Restore Mailup

---

_data/roadmap.yml

roadmap designers italia 2019

---

_kits/it/web-development-kit.md

Fix typo in web-development-kit

---

_kits/it/comuni.md
_kits/it/scuole.md
_kits/it/update
_layouts/kitsindex.html
_projects/it/siti-web-scuole.md

Per creare il sito di una scuola utilizza il [documento di architettura dell'informazione](https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit?usp=sharing) come guida per la struttura dei contenuti, il sistema di navigazione e i flussi di interazione. Con i template html potrai realizzare il front-end dell’intero sito.
Il kit è indipendente rispetto alle scelte tecnologiche di una scuola (per esempio la scelta di un CMS). Rappresentando uno standard, favorisce l’utilizzo di soluzioni tecnologiche condivise e la diffusione di best practice. 
Vai ai template
Un primo sito realizzato in wordpress e basato su questi materiali è già disponibile in modalità open source e rappresenta la soluzione più rapida per aderire al nuovo modello di sito scolastico.
Vai …

Testo introduttivo al kit scuole

---

_projects/it/web-analytics-italia.md

@pdavide qui l'aggiornamento. Ho inserito un link diretto a WAI perciò magari va mergiata subito dopo che WAI è veramente online! :-P

aggiornamento progetto WAI per avvio fase beta

---

_includes/guidesbanner.html
_pages/it/partecipa.md

update "Home & Linee Guida” banner, removed block from "partecipa"

---

Dockerfile
README.md
package.json

chore: add Docker development environment

---

_data/menu_items.yml

chore: remove Home link from menu

---

_modelli/it/comuni.md
_modelli/it/scuole.md

a new branch for content entry

new branch for content entry

---

_pages/it/partecipa.md

chore(content): use correct typographic apostrophe

---

_modelli/it/scuole.md

Added link to the new avviso 1.4.1

fix/ link to avviso 1.4.1

---

_layouts/modello.html
_modelli/it/comuni.md

We've fixed the two links to both mobile and desktop version of "Richiesta mensa scolastica" prototype.

Fixed prototypes wrong links

---

_posts/2022-07-27-Nuove-Linee-guida-e-Manuale-operativo-di-design.md

This reverts commit 2454d096aef1b14ad29ffd4d6b66e6518575d6a3.

chore(content): re-publish design guidelines & manual news

---

_data/attivita.yml

Aggiornato il piano attività con la pubblicazione del nuovo modello di sito comunale.

fix/Aggiornamento piano attività

---

_modelli/it/comuni.md

Added link to "Libreria Organismi"

Added link to new resource

---

_kits/it/web-analytics.md

Web analytics update

---

src/js/globals.js
src/templates/tmpl-base.js

fix: mouse focus script in build

---

src/components/button/button.js
src/components/card/card.js
src/components/chip/chip.js
src/components/feedback/components/form-no/FormNo.js
src/components/footer-brand/footer-brand.js
src/components/footer-main/footer-main.js
src/components/footer-small/footer-small.js
src/components/header-center/header-center.js
src/components/header-post/header-post.js
src/components/header-pre/header-pre.js
src/components/img-full/img-full.scss
src/components/last-update/last-update.js
src/components/link-custom/link-custom.js
src/components/link/link.js
src/components/list-item/list-item.js
src/components/list/list.js
src/components/megamenu/megamenu.js
src/components/nav-position/nav-position.js
src/components/simple-cta/simple-cta.js
src/components/tag/tag.js
src/data/footer.yaml
src/data/header.yaml

feat: gatsby link component

---

src/components/header-menu-link/header-menu-link.js
src/components/header-menu-link/header-menu-link.scss
src/components/megamenu/megamenu.js
src/components/megamenu/megamenu.scss

fix: header megamenu a11y

---

src/components/subscribe/subscribe.js
src/data/footer.yaml

feat: add mailing list registration

---

src/components/nav-sidebar/nav-sidebar.js
src/components/nav-sidebar/nav-sidebar.scss

fix(a11y): sidebar button instead of a #524

---

src/pages/community.yaml
src/pages/design-system.yaml
src/pages/modelli.yaml
src/pages/norme-e-riferimenti.yaml
src/pages/progetto.yaml
src/pages/risorse-per-progettare.yaml
src/templates/tmpl-level-1-community.js
src/templates/tmpl-level-1.js

@Fupete adds new `metadata.activeLabel` on level 1 yaml files to handle match with menu link label.

fix: level 1 active page style on menubar

---

src/components/list-item/list-item.js
src/components/list/list.js

feat: make share-on-social menu work

---

src/components/feedback/feedback.js

fix(a11y): don't stuff content into h2 in feedback UI

---

gatsby-config.js
package-lock.json
package.json

Temporarly use Matomo Cloud while we wait for a definive solution.
Fix #434.

feat: add web analytics with Matomo

---

src/components/content-collapse/contentCollapse.js

Changed content collapse icon

---

.github/workflows/lighthouse.yml

Show all links we checked with Lighthouse in the resulting comment and remove PWA score as the site is not a PWA anyway.

chore(lighthouse-ci): show all links and remove PWA

---

src/data/content/design-system/fondamenti/principi-e-intenzioni.yaml

Fix typo in principi-e-intenzioni.yaml

---

src/data/content/community.yaml
src/data/content/community/piano-attivita.yaml
src/data/content/modelli/comuni.yaml
src/data/content/modelli/scuole.yaml
src/data/content/norme-e-riferimenti.yaml
src/data/content/norme-e-riferimenti/manuale-operativo-di-design.yaml
src/data/content/risorse-per-progettare/comprendere/analisi-del-contesto.yaml
src/data/content/risorse-per-progettare/comprendere/esperienza-utente.yaml
src/data/content/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.yaml
src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione.yaml
src/data/content/risorse-per-progettare/progettare/co-progettazione.yaml
src/data/content/risorse-per-progettare/progettare/contenuti-e-linguaggio.yaml
src/data/content/risorse-per-progettare/progettare/prototipazione.yaml
src/data/content/risorse-per-progettare/realizzare/costruzione-interfaccia.yaml
src/data/content/risorse-per-progettare/realizzare/sviluppo-interfaccia.yaml
src/data/content/risorse-per-progettare/validare/test-di-usabilita.yaml
src/data/content/risorse-per-progettare/validare/web-analytics.yaml

Added more redirects to the YAML files.

Feat: next redirects

---

src/data/content/community/notizie/20230328-aperte-le-iscrizioni-della-seconda-edizione-del-corso-qualita-dei-servizi-digitali.yaml

Fixed markup in our latest news.

fix: next: wrong markup

---

src/components/hero/hero.js

fix: shareColor

---

src/components/header-center/header-center.scss
src/components/header-menu-link/header-menu-link.js
src/components/header-menu-link/header-menu-link.scss
src/components/header-nav/header-nav.js
src/components/header-nav/header-nav.scss
src/components/header-post/header-post.scss
src/components/header/header.js
src/components/header/header.scss

fix: sticky header spacing

---

src/components/header-slim/header-slim.js
src/components/header-slim/header-slim.scss
src/data/header.yaml

fix: slim header behaviour

---

src/data/content/note-legali.yaml
src/data/content/privacy-policy.yaml
src/data/footer.yaml

feat: content updates (legal pages)

---

.github/workflows/deploy.yml
package-lock.json
package.json

chore(ci): use GitHub actions for deploying

---

src/data/content/community/notizie/20220325-atlante-della-trasformazione-digitale.yaml
src/data/content/community/notizie/20221220-ecco-l-anteprima-del-nuovo-designers-italia.yaml
src/data/content/community/notizie/20230504-design-system-pubblicata-la-versione-ufficiale-dello-ui-kit-italia.yaml
src/data/content/community/notizie/20230506-tutti-gli-eventi-di-designers-italia-a-maggio.yaml
src/data/content/index.yaml
src/data/content/ricerca.yaml

fix: switch prossima and vercel urls

---

src/data/content/community/notizie/20230328-aperte-le-iscrizioni-della-seconda-edizione-del-corso-qualita-dei-servizi-digitali.yaml
src/data/content/norme-e-riferimenti.yaml

content: clean norme e riferimenti + minor typo

---

src/components/header-pre/header-pre.js

Make the no-restricted-globals lint pass.

refactor: use window global instead of location

---

README.md

Just to check #530 now works for PR from forks.

doc: remove whitespace

---

src/components/button/button.js
src/components/card/card.js
src/components/footer-brand/footer-brand.js
src/components/footer-main/footer-main.js
src/components/footer-small/footer-small.js
src/components/header-center/header-center.js
src/components/header-post/header-post.js
src/components/header-slim/header-slim.js
src/components/last-update/last-update.js
src/components/link-custom/link-custom.js
src/components/list-item/list-item.js
src/components/nav-position/nav-position.js
src/components/simple-cta/simple-cta.js

fix: noreferrer external links if _blank target

---

src/data/content/community/eventi/20230519-accessibility-days-2023-l-accessibilita-nello-sviluppo-front-end-di-servizi-pubblici-le-risorse-del-design-system-del-paese.yaml

Fix: Accessibility Days event details

---

.github/workflows/deploy.yml

chore: fix the last updated date in pages

---

src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml

Fixed date + removed the image temporarily.

Fix/News "Fondamenti di linguaggio"

---

src/data/content/community.yaml
src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml
src/data/content/index.yaml
src/data/header.yaml

I updated the link in the banner under the main navigation and fixed the "Writing foundations" news card in the Community section.

fix: banner update + fixed card thumbnail

---

src/data/content/community/notizie/20221220-ecco-l-anteprima-del-nuovo-designers-italia.yaml
src/data/content/community/notizie/20230327-raccontaci-cosa-ne-pensi-di-designers-italia-e-developers-italia.yaml
src/data/content/design-system/fondamenti/accessibilita.yaml
src/data/content/design-system/fondamenti/versionamento.yaml
src/data/content/risorse-per-progettare.yaml
src/data/content/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso.yaml
src/data/content/risorse-per-progettare/comprendere/esperienza-utente.yaml
src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione/individua-i-contenuti.yaml
src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione/organizza-i-contenuti.yaml

feat: tags-2nd-iteration

---

src/data/content/modelli/comuni.yaml
src/data/content/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali.yaml
src/data/content/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/progetta-il-flusso-di-servizio.yaml

The links to Figma files for 'Modello Comuni' have been updated.

fix: links to Figma files

---

src/components/table/table.js

feat: enable markdown on tables

---

src/components/component-view/component-view.js
src/components/table/table.js
src/components/table/table.scss
src/data/content/design-system/fondamenti/technical-template.yaml
src/pages/{content.relativePath}.js

feat: enhance tables

---

src/components/section-editorial/section-editorial.scss

fix: section-editorial spacing just for design system section

---

src/data/content/risorse-per-progettare/comprendere.yaml

Changed the subheading to fix service design jargon and avoid misunderstandings with 'scenario of use' as a tool

content: Update comprendere.yaml

---

src/data/content/community/notizie/20231024-nuovi-rilasci-del-design-system-del-paese-e-delle-risorse-di-progettazione-e-sviluppo.yaml

…orse-di-progettazione-e-sviluppo.yaml
link added to the video player news

fix: link added to DS news

---

src/components/img-full/img-full.scss

Improves the responsiveness of the img-full component when used in design system pages.

fix: ds img-full margins

---

src/data/content/community/eventi/20231128-realizzare-interfacce-pubbliche-di-qualita-e-piu-accessibili-grazie-al-design-system-del-paese.yaml

…ssibili-grazie-al-design-system-del-paese.yaml

content: ANCI webinar SEO fix

---

src/components/back-to-top/back-to-top.js
src/components/feedback/feedback.scss
src/components/header-menu-link/header-menu-link.scss
src/components/highlight/highlight.scss
src/components/nav-sidebar/nav-sidebar.js
src/components/nav-sidebar/nav-sidebar.scss
src/components/tooltip/tooltip.js
src/scss/bootstrap-italia-TEMP-FIXES-REMOVEME.scss
src/scss/bootstrap-italia-temp-fixes.scss
src/templates/design-system-index.js

Trying to leave just the minimum amount of hacks as possibile. 
To be resolved soon on BSI, see https://github.com/italia/bootstrap-italia/issues/1009
Fix #1038 .

fix: refactor all stacking issues (z-index)

---

package-lock.json
package.json
src/scss/custom.scss

Css for media player is already included in the latest version of Bootstrap Italia.

fix: remove useless css for media player

---

src/data/content/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso.yaml
src/data/content/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.yaml
src/data/content/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/rielabora-le-informazioni.yaml
src/data/content/risorse-per-progettare/comprendere/questionario-online/sintetizza-i-risultati-della-ricerca.yaml
src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione/organizza-i-contenuti.yaml
src/data/content/risorse-per-progettare/progettare/co-progettazione/co-progetta-i-contenuti.yaml
src/data/content/risorse-per-progettare/progettare/co-progettazione/co-progetta-l-esperienza-d-uso.yaml
src/data/content/risorse-per-progettare/progettare/contenuti-e-linguaggio/crea-il-linguaggio-del-touchpoint-digitale.yaml
src/data/content/risorse-per-progettare/progettare/prototipazione/definisci-i-flussi-di-interazione.yaml
src/data/content/risorse-per-progettare/validare/test-di-usabilita/rielabora-e-condividi-i-risultati-dei-test-di-usabilita.yaml

Change the generic slide icon to the precise icon of `it-file-ppt` for PPT files.

fix: icons ppt (kits)

---

src/components/list-archive-all-tags/list-archive-all-tags.js
src/components/list-archive-ds-tags/list-archive-ds-tags.js
src/data/dsnav.yaml
src/scss/custom.scss

See tag lists in pages: `/argomenti/` and `/design-system/componenti/`
See also: #851

feat: and fix badges inside tags

---

src/data/content/design-system/fondamenti/colori.yaml

Fixed wrong colors HEX codes on the foundation page.

fix: colors hex

---

src/components/content-collapse/content-collapse.js
src/components/dropdown/dropdown.scss

The SectionIntro button lacks style. 
And the drop-down items lack the white-space property. 
I think I cleaned up too much SCSS yesterday ;-) Let's restore these couple of things ASAP.

fix: BSI 2.8.1 local styling

---

src/data/content/community/media/20210319-progettare-servizi-pubblici-digitali-piu-equi-e-sostenibili.yaml

Fixed wrong youtube url with `/live/` in an old media.

fix: youtube url media post 20210319

---

src/components/text-image-cta/text-image-cta.js

fix: https://github.com/italia/designers.italia.it/pull/1203#issuecomment-1941368550

fix: cta spacing

---

src/data/content/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.yaml

Corretto il link all'indice dei templates statici.

fix: link path

---

src/data/content/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.yaml

I updated the link to the hi-fi layouts file, adding the one published in the Figma Community.

content: change link to Figma file

---

src/data/content/modelli/aziende-sanitarie-locali.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/comprendi-lo-stato-dell-arte.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/definisci-architettura-e-contenuti.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/realizza-l-interfaccia-del-sito-asl.yaml

content(fix):modello-asl-architettura

---

src/data/content/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/realizza-l-interfaccia-del-servizio-digitale-comunale.yaml
src/data/content/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.yaml

Using the `it-github` instead of `it-figma`

fix: change icon link

---

src/data/content/modelli.yaml
src/data/content/modelli/aziende-sanitarie-locali.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/realizza-l-interfaccia-del-sito-asl.yaml
src/data/content/modelli/comuni.yaml
src/data/content/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/realizza-l-interfaccia-del-servizio-digitale-comunale.yaml
src/data/content/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.yaml
src/data/content/modelli/musei-civici.yaml
src/data/content/modelli/musei-civici/adotta-il-modello-di-sito-per-i-musei-civici/realizza-l-interfaccia-del-sito-del-museo-civico.yaml
src/data/content/modelli/scuole.yaml
src/data/content/modelli/scuole/adotta-il-modello-di-sito-scolastico/realizza-l-interfaccia-del-sito-scolastico.yaml

Updated the UI resource links, adding GitHub and reviewing content.

content: UI resource links

---

src/data/content/community/piano-attivita.yaml

Shifted already performed activities to the section 'I risultati che abbiamo raggiunto' for each activity changed links and added image for most relevant milestone.

Update progress as to May piano-attivita.yaml

---

src/data/content/index.yaml

Added news about contribution model.

content: homepage news

---

src/data/content/community.yaml

Reduced number of cards to better fit. From 7 to 4...

Update card eventi.yaml

---

src/data/content/modelli/scuole.yaml

Corrected a typo in the "In breve" section on the main page of modello Scuole

content(fix):modello-scuole-typo

---

src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/definisci-architettura-e-contenuti.yaml

Updated link to the XLSX version of the IA file, as it was wrongly pointing to the ODS version

content(fix):file-IA-ASL

---

src/data/content/community.yaml

Added card latest created event page to community section

Update content community.yaml

---

src/data/content/community.yaml

FIX: Removed oldest card to keep 6 online in preview

Update content articoli community.yaml

---

src/data/content/community.yaml

Added card for latest event and removed oldest to stock to 4.

Update event card community.yaml

---

src/components/search-main/search-main.js

Aggiunte le classi di Bootstrap per correggere bug visualizzazione `input`

fix: input search

---

src/data/content/design-system/fondamenti/linguaggio.yaml

Ciao, rivedendo il fondamento per necessità ho notato un typo e qualche possibilità di miglioramento.

content: fix "Linguaggio"

---

src/data/content/design-system/fondamenti/microtesti.yaml

Fixed the color of DO and DONTS badges.

fix: do and donts

---

src/data/content/community/eventi/20241119-community-lab-design-system-italia.yaml

Mi ero dimenticata che esiste l'argomento 'Community lab, lo ho aggiunto tra i tag.

Update tag 20241119-community-lab-design-system-italia.yaml

---

src/components/list-item/list-item.js
src/components/list-item/list-item.scss

feat: new download resources list for BSI 2.11.0

---

src/data/content/design-system/fondamenti/linguaggio.yaml
src/data/content/design-system/fondamenti/versionamento.yaml
src/data/dsnav.yaml

chore(release): design system .italia v1.2.0 🚀 🇮🇹

---

src/data/content/modelli/contribuisci-ai-modelli/come-contribuire-ai-modelli.yaml

fix: url typos

---

src/data/content/community/eventi/20240604-lancio-nuovo-modello-musei-civici.yaml

Changed the tag for consistency with previous ones

Update tag 20240604-lancio-nuovo-modello-musei-civici.yaml

---

src/data/content/design-system/fondamenti/versionamento.yaml
src/data/dsnav.yaml

chore(release+deps): design system .italia v1.4.3 🚀 🇮🇹 and update BSI to 2.13.4

---

src/data/content/design-system/fondamenti/versionamento.yaml
src/data/dsnav.yaml

chore(release): design system .italia v1.6.0 🚀 🇮🇹

---

src/data/content/community/eventi/20250528-Community-call-aziende-sanitarie-locali.yaml
src/data/content/community/eventi/20250528-community-call-aziende-sanitarie-locali.yaml

…li.yaml
Added content, links, card and image still missing

Created new event page 20250528-Community-call-aziende-sanitarie-locali

---

src/components/nav-sidebar/nav-sidebar.scss

Corregge temporaneamente il bug introdotto con la larghezza della `navbar-collapsable` da Bootstrap Italia v2.15

fix: navbar width

---

src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/comprendi-lo-stato-dell-arte.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/definisci-architettura-e-contenuti.yaml
src/data/content/modelli/aziende-sanitarie-locali/adotta-il-modello-di-sito-asl/realizza-l-interfaccia-del-sito-asl.yaml
src/data/content/modelli/musei-civici/adotta-il-modello-di-sito-per-i-musei-civici/comprendi-lo-stato-dell-arte-del-sito-del-museo-civico.yaml
src/data/content/modelli/musei-civici/adotta-il-modello-di-sito-per-i-musei-civici/definisci-architettura-e-contenuti-per-il-sito-del-museo-civico.yaml
src/data/content/modelli/musei-civici/adotta-il-modello-di-sito-per-i-musei-civici/realizza-l-interfaccia-del-sito-del-museo-civico.yaml

Ho aggiunto il riferimento alle risorse di sviluppo sulle pagine dei modelli ASL e Musei

content(feat):modelli-risorse-sviluppo

---

README-EN.md
README.md

Come da soggetto. 
Dobbiamo mergiare le due PR con le guide "how-to" prima di questa.

chore: update README + README-EN

---

src/data/editorial-board/highlighted-cards.yaml

Fixed content: added 'Partecipa' removed old 'Contenuti e linguaggio'

Update editorial board home page highlights.yaml

---

src/data/content/design-system/fondamenti/versionamento.yaml
src/data/dsnav.yaml

chore(release): design system .italia v1.9.1 🚀 🇮🇹
