_includes/card.html
_includes/home/block-6.html
_plugins/MediumImporter.rb

L'utilizzo di `latest` permette di usare il parametro `count` per ottenere più di 7 post.
Alcune modifiche necessarie:
- rimossa versione inglese (post già presenti nella chiamata al nuovo feed)
- i post sono in un oggetto diverso all'interno del JSON
- controllo post senza `previewImage` (al momento solo uno)

Medium: importazione di tutti i post

---

README.md

I kit sono ospitati o lincati  nel repo e esiste la possibilità di creare issue relative ai kit
NOTA
in tutte le pagine di presentazione dei kit sarebbe opportuno inserire creare un paragrafo (diciamo sotto alle linee guida) in cui inserire il link al repo specifico - se presente e in altrenativa appunto il link alle issues
@francescozaia 
Qui l'esempio in cui il kit (ad esempio lo user journey) non abbia un repo github specifico
Come partecipare
Grazie a dei repository pubblici, è sufficiente avere un account su GitHub per proporre modifiche o aggiungere nuovi elementi ai kit, attraverso delle pull request o delle issue.
https://github.com/italia/designers.italia.it/issues

Inserito riferimento ai kit

---

.circleci/config.yml

Adds Cache invalidation, which is useful to fix build issues
when circleci cache corrupts.
Prefixing the cache with a `v0` like we have in other repos.

Fix #141. Add versioning to enable cache invalidation.

---

_posts/2022-03-25-Community_call_design_sinergia_universita_PA.md

mobilizon.it is down, let's remove the link from the news

chore: remove mobilizon link in news

---

Gemfile.lock

bundler > 2.1 needs to be instructed on what architectures to use when fetching the binary packages, otherwise it'll always try to compile the gem.
The Vercel preview uses bundler 2.3, so let's bump the version.

chore(build): fix the build when using bundler > 2.1

---

src/components/feedback/components/form-no/FormNo.js
src/components/feedback/feedback.scss
src/components/label-textarea/label-text-area.js

Copy the TextInput component to workaround and use it for the feedback UI textarea to workaround the overlapping label.
Fix #528.

fix: workaround for textarea labels overlapping the content

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json
src/data/content/community/piano-attivita.yaml

Implement client side redirects from YAML content in src/data/content
by using the metadata.redirect_from key.
Small gotcha: redirects don't get created locally in development
mode, but they do only in production (and preview), because
gatsby-plugin-meta-redirect uses `onPostBuild()` which is invoked only
after `npm run build`.
Fix #420.

feat: implement client side redirects

---

package-lock.json
src/pages/{content.relativePath}.js

Don't fail getting the last modified time when a new page is created locally and has not been yet commited to the repo.
Fix #648.

fix: add fallback for the git last modified time

---

.github/workflows/lighthouse-pr-comment.yml
.github/workflows/lighthouse.yml

GitHub pull_request workflows are run within the context of the forked
repo and they can't comment on they own PR.
Using pull_request_target would be a security hole since we need to run
PR-provided arbitrary code to build the site.
The only viable option is `workflow_run` that detect when the
Lighthouse job has finished, as it is run in the context of the parent
repo.
That's extremely convoluted and not ideal because it doesn't even
provide full protection (see below), but it's a GitHub limitation
that needs to be fixed on their side with something like a
new 'comment-write' permission on ephemeral tokens.
There's still a way for a malicious PR to be annoying by
commenting on other PRs but it's not a security issue
Fix https://github.com/italia/designers.italia.it/issues/530.

chore(ci): make lighthouse work in PR from forks

---

gatsby-config.js

Make gatsby-plugin-matomo use MATOMO_SITE_URL and MATOMO_SITE_ID environment variables.
Fix #716.

feat: make Matomo tracking configurable with env variables

---

src/components/icon/icon.js
src/components/nav-sidebar/nav-sidebar.js
src/components/numbers/numbers.js

As reported by @cfabry
@astagi just a reminder: we have to check & review Bootstrap Italia `<SVG>`s maybe they (the icons) are missing a `role="img"` also there.

fix: svg a11y markup

---

.github/workflows/lighthouse-pr-comment.yml

`download-artifact` doesn't support getting artifacts from a different workflow
https://github.com/actions/download-artifact/issues/172
Let's use a third party action that does it.
Fix #530.

chore(ci): properly get the Lighthouse artifact

---

src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione.yaml
src/data/content/risorse-per-progettare/progettare/seo.yaml

The "In breve" short description text for the kit was wrong; I replaced it with the correct one.
During this process, I also noticed a typo + a possibile improvement in the "SEO" kit short description, so I changed it as well.

Fix: Kit "Architettura dell'informazione" short description

---

gatsby-config.js

The code is not completly linted yet (#848), so let's disable the check during development.

chore: disable the live linting during development

---

README.md
gatsby-config.js
package-lock.json

When using `chore(content-skip)` somewhere in the commit message for commits that change src/data/content/, the last modification time in the generated pages won't be updated.

feat: way to skip the generation of last modification time

---

src/data/content/progetto/formazione-e-disseminazione.yaml

The dark editorial box moved to the bottom of the page, so to improve the findability of the content about 'Promozione'.

content: update formazione-e-disseminazione

---

src/components/chip/chip.scss
src/scss/vars.scss

fix: #1098 
To simplify as soon as this fix https://github.com/italia/bootstrap-italia/pull/1020 will be merged in BSI.

fix: chips margins

---

src/components/footer-main/footer-main.scss

See #851. 
This mini fix resolve the Lighthouse minimum touch size errors in the footer (community links) @bfabio 🎉 
The error in the chips was already fixed last week with the corrections to the Bootstrap Italia component spacing. 
ps. this is a more "precise" approach than https://github.com/italia/designers.italia.it/pull/917, which remains just an interesting POC, I think we can close that, no? 
pps. maybe we can check this list spacing in the original Bootstrap Italia footer component. And if needed open a new PR with this fix there.

fix: community links SEO min spacing

---

.github/workflows/lighthouse.yml

Update the Lighthouse report message so to display the emotes.
Looks like GitHub doesn't expand shortcodes to emotes in headers anymore.

chore(ci): update Lighthouse report message

---

src/components/footer-brand/footer-brand.js

@astagi I solved a11y minor problem about footer logos. We don't need `aria-label`, but to use the right alternative texts (describing the function and not just the image) for those logo images...

fix: footer logos images alt text

---

src/components/nav-sidebar/nav-sidebar.js
src/data/dsnav.yaml
src/data/header.yaml
src/data/skiplinks.yaml

Fix: https://github.com/italia/designers.italia.it/issues/1147
We will need to investigate further how to improve the `navscroll` component of Bootstrap Italia that we are currently repurposing for the sidebar of the design system. We will open an issue as soon as this is merged. 
This PR fix the urgent "focusable" part, now it is. However the keyboard "pattern" is still not perfect.

fix(a11y): enhance navigation and fix ds nav mobile focus

---

src/data/content/community/notizie/20230927-partono-i-lavori-per-il-modello-di-sito-web-per-i-musei-civici.yaml

…-musei-civici.yaml
I removed the link to the CTA about filling up the form, as that has been closed a couple of months ago.

content(fix): remove outdated CTA from a news

---

src/components/feedback/feedback.js

Probable cause: this commit on Bootstrap Italia: https://github.com/italia/bootstrap-italia/commit/fc88721743c838cec67946f7b0865ee6aba809af
cc @astagi @zetareticoli

fix: feedback radio fieldset inline spacing

---

.github/workflows/deploy.yml
package.json

This PR removes the "clean" function in the deployment workflow to enable the use of Gatsby Cache.

chore: add build ci specific workflow
